### ISSUE TITLE
State meesed up when reserving/canceling a place when more places are available

### ISSUE THREAD

**Issue by tom-rybka** [fedorjaro/repark-issues#10]
1. The date has more than 1 place available. 
2. When clicked on a date, the app has created a reservation. However, it didn't change the state of a date fir me as reserved.
3. When I tried to cancel the reservation right after, it just reserved yet another place for me.
4. I had to reserve all the available places first (the state of a date has changed to "reserved"/yellow), before the app started to cancel the reserved places for me.
5. Once I clicked X-times to cancel all the previously booked places, the date returned to the default "free" state.

**Comment by fedorjaro** [comment]
This bug will be fixed in version 1.1,
Thank you Tom for reporting.
