### ISSUE TITLE
Add reserved spot number for a day at prominent space.

### ISSUE THREAD

**Issue by honzapaces** [fedorjaro/repark-issues#18]
When I'm trying to park I would welcome that the first thing I see is the number I have reserved for today.

See mockup for example.
![repark-mockup](https://user-images.githubusercontent.com/3212999/75029663-c6810200-54a2-11ea-9862-ae63522b0155.png)

**Comment by jaroslav-fedor-swi** [comment]
Thank you for reporting the feature. It has been implemented and will be deployed in the next release.
![image](https://user-images.githubusercontent.com/56395774/86475304-b3314d80-bd44-11ea-9099-6f2c0853f426.png)

**Comment by fedorjaro** [comment]
Thank you for reporting the feature, it will be deployed with next release.
