### ISSUE TITLE
My reservations order: Last reservation is not displayed as last (on the bottom of list) and general confusion which one is payed

### ISSUE THREAD

**Issue by invertedburger** [fedorjaro/repark-issues#37]
For some reason my latest reservation is not on the bottom of the list, but on the place before. This was confusing, I almost payed the other guy twice. I would also be happier if the guys who are providing place were forced to confirm the payment, or maybe if they don't "complain" for a few days than the reservation is marked as green (payed). Don't know what is the best solution, most of my reservation are red, I hope I paid them.  :)

**Comment by fedorjaro** [comment]
fixed in v1.8
