### ISSUE TITLE
Reserved parking slot was occupied by someone else

### ISSUE THREAD

**Issue by david-sevcik** [fedorjaro/repark-issues#49]
### Actual behavior
13.4.2022 I reserved parking spot on next day (14.4.2022). I also received a confirmation (in the picture below) and paid the fee. But next day, when arrived in the office, the parking slot was occupied by someone else, so I look in the app and the reservation was gone, like it never happened. It also disappeared from Payments.
Not sure, what exactly happened, there is no other prove of what I did or not except the email confirmation.
I don't think I canceled it, because I also went to Payments page to pay the fee and at this moment, it was still reserved by me - it was listed in this page. It should be canceled some time after the payment and it seems unlikely  to happen by my own action, but ok, still can be my fault.

![image](https://user-images.githubusercontent.com/63638505/163973514-7dcd65fe-9a7d-4f48-ae98-4967b6362db0.png)

### Expected behavior

- If this is my fault and I really canceled it, then I except to receive some confirmation like the one, that I received when I reserved the spot. And also see my actions in some log - maybe in the Payments log, the payment will be listed there as canceled
- And if it was not canceled by my action, then rather if it will not happen again.

**Comment by matusbzk** [comment]
This happened to me too - reservation disappeared without any trace that it ever happened (I have the confirmation email though)

**Comment by fedorjaro** [comment]
This is foxed in v1.7
