### ISSUE TITLE
Cannot delete requested reservation

### ISSUE THREAD

**Issue by matusbzk** [fedorjaro/repark-issues#51]
When I request a reservation for a date when no places are available, the day changes to red - Requested reservation.

It's not possible to delete this, when I click it again, the popup says that request has been deleted, but it's not - it's still red, and it will reserve a place for me if some becomes available.
![image](https://user-images.githubusercontent.com/34398481/186167917-17b9e55a-79f4-42d2-b184-fd439cf71c0b.png)

**Comment by milankarak** [comment]
Happened to me as well. Tried to cancel it few times but faced the same problem. On given day I received parking spot even I was not in the office and I could not cancel it neither.

**Comment by manisha-sharma-swi** [comment]
Facing same problem. Not able to cancel requested reservation.

<img width="1240" alt="image" src="https://user-images.githubusercontent.com/109793177/192459320-b07c6935-1fb7-453b-bc07-c85ce141c42a.png">

**Comment by fedorjaro** [comment]
This is fixed.
