### ISSUE TITLE
Assigned spot is not chosen randomly

### ISSUE THREAD

**Issue by matusbzk** [fedorjaro/repark-issues#54]
Somebody was standing on place I had reserved (possibly because of https://github.com/fedorjaro/repark-issues/issues/53 or some other issue; the other person had the place reserved too).
I tried to cancel the reservation and get a new one, but the same spot was still being assigned to me.

There were 6 free places, so it was not the only free space.

**Comment by fedorjaro** [comment]
Based on logs I guess that Daniel canceled his reservation few seconds before you got it. #53 is fixed so closing this one too.
