### ISSUE TITLE
Cannot cancel reservation

### ISSUE THREAD

**Issue by matusbzk** [fedorjaro/repark-issues#55]
I cannot cancel my reservation, and I couldn't cancel it even few days before the actual reservation date. When I click there, the page shows message about canceling it, but the page still shows that the reservation exists.

![image](https://user-images.githubusercontent.com/34398481/190124275-5466fc32-0cce-4078-a7e2-95c82ae82786.png)

**Comment by manisha-sharma-swi** [comment]
I have faced same problem twice when I tried to cancel my reservation. I checked with the owner of the spot and he mentioned that the spot is still reserved by me.

**Comment by fedorjaro** [comment]
What time did you try to cancel reservation?

**Comment by matusbzk** [comment]
> What time did you try to cancel reservation?

Evening the day before, maybe around 7 or 8 pm.

**Comment by manisha-sharma-swi** [comment]
> What time did you try to cancel reservation?

I tried during the day before. Around 11 am maybe and then kept trying in afternoon as well but it was yellow

**Comment by fedorjaro** [comment]
Can you try again? I found one bug which was introduced with email notifications.

**Comment by fedorjaro** [comment]
Tested and seems to be working. Pls reopen if you are still not able to cancel your reservation.

**Comment by matusbzk** [comment]
I have this issue again - I'm trying to cancel the reservation for tomorrow - February 14th. When I click there, the page shows message about canceling it, but the page still shows that the reservation exists.

I do not have rights to reopen the issue.
