### ISSUE TITLE
Would it be possible to see also the history of payment?

### ISSUE THREAD

**Issue by petr-mokros-swi** [fedorjaro/repark-issues#58]
![image](https://user-images.githubusercontent.com/83069564/199982714-f44aa4fc-a92e-45fb-b910-26254d0d87cc.png)

For example here - Jan already reserved and paid my place some time ago... but in Internet banking, once a user does not write down explicitly which days he/she is paying then it is hard to know if the payment is for something in the past or for that which is missing to pay...
![image](https://user-images.githubusercontent.com/83069564/199983323-f6dfd8ad-6e8f-431f-b08e-15c5f4ce6de3.png)

With the ability to see the historical payment, these guesses would be easier :)

Thank you

**Comment by fedorjaro** [comment]
If all payments are settle, you can see all historical payments. Is that good enough?

**Comment by fedorjaro** [comment]
fix in version 1.8 message will be something like `REPARK: Payment from admin to
last for spot 123 during date(s): 2023-04-15`
