### ISSUE TITLE
Wrong order of historical payment

### ISSUE THREAD

**Issue by petr-mokros-swi** [fedorjaro/repark-issues#59]
![image](https://user-images.githubusercontent.com/83069564/199984213-b44699a0-9d7a-4d3e-a62f-a1e8c00f51cc.png)

As you can see here the dates are not in order - it is hard to check (especially in the case of the longer history) if the payment was done or not... it is simply confusing. It does not matter in which order it would be, but at least some order would be great :).

Thank you

**Comment by fedorjaro** [comment]
fixed in v 1.8
