### ISSUE TITLE
Missing ability to settle just selected pending payments

### ISSUE THREAD

**Issue by PetrVilem** [fedorjaro/repark-issues#62]
When I get paid for historical set of reservations but same person has another resevation with future date (which typically does not get paid in advance), I am unable to make this "partial" settlement properly.

![image](https://user-images.githubusercontent.com/64415657/208063433-dc568615-40e3-4194-9814-a834ede96753.png)

Ability to settle custom selected reservations only would be ultimate solution, but another possible improvement would be at least adding "Settle past reservations" besides "Settle all".

**Comment by jvilimek** [comment]
makes sense to me too

**Comment by fedorjaro** [comment]
done in version 1.6

**Comment by PetrVilem** [comment]
![image](https://user-images.githubusercontent.com/64415657/231845272-cbf71d69-e570-4230-b353-c22c942d5089.png)
I can see new small "Settle" button on single item level, but it is not clickable. Moreover, ability to settle all is gone (replaced by Errror) :(
