### ISSUE TITLE
Requested spot does not appear in the UI

### ISSUE THREAD

**Issue by jvilimek** [fedorjaro/repark-issues#66]
Hi & thanks for the great app.
However, I have the following issue: this morning I requested a spot, and shortly after an email came that I have successfully reserved a spot (66/II) but this spot is not shown in the [UI](https://repark.space/), nor in the payments...whom shall I thank (and pay) for the spot then?

1. Is this a bug, that the spot does not pop up in the UI? 
2. Is there a way to discover an owner of a spot to write him/her directly?

Thanks
J.

**Comment by fedorjaro** [comment]
checking logs:
jiri canceled reservation
```
INFO 2023-02-14 07:52:37,880 ReservationManager Canceled reservation {"id": 6345, "date": "2023-02-14", "place": "66/II", "paid": false, "reserved": "jiri.*******@********.com"}
```

reservation was updated to jan, but due to bug never saved, but mail went out..
```
INFO 2023-02-14 07:32:12,828 ReservationManager Created reservation {"id": 6356, "date": "2023-02-14", "place": "null", "paid": false, "reserved": "Jan.*******@*******.com"}
INFO 2023-02-14 07:52:37,892 ReservationManager Sending email subject: Your spot reservation was changed! {"id": 6345, "date": "2023-02-14", "place": "66/II", "paid": false, "reserved": "Jan.*******@*******.com"}
INFO 2023-02-14 07:52:38,770 ReservationManager Sending email to: Jan.*******@*******.com
INFO 2023-02-14 07:52:39,649 ReservationManager Updated reservation {"id": 6345, "date": "2023-02-14", "place": "66/II", "paid": false, "reserved": "null"}
```
I believe this should be fixed and it is covered with unit test now.
