### ISSUE TITLE
Reservation not being cancelled

### ISSUE THREAD

**Issue by manisha-sharma-swi** [fedorjaro/repark-issues#67]
I tried to cancel a booking for Wednesday a day before i.e. Tuesday. Every time I clicked on the reservation, the pop said reservation is cancelled but it still kept it yellow and reserved.

<img width="1320" alt="image" src="https://user-images.githubusercontent.com/109793177/229097194-e700c295-b53b-436d-a3fa-6c957b4b548b.png">

**Comment by fedorjaro** [comment]
This bug should be fixed. LMK if you hit it again.
