### ISSUE TITLE
Reserved spot is no longer visible 

### ISSUE THREAD

**Issue by manisha-sharma-swi** [fedorjaro/repark-issues#68]
I had a spot reserved for 20th April and I don't see it now on RePark. Do I need to book again?
<img width="672" alt="image" src="https://user-images.githubusercontent.com/109793177/231120055-684b0125-e1f4-4a1b-81cd-d05b7be598ac.png">

**Comment by fedorjaro** [comment]
Sorry, must accidentally delete it. Should be back now. Sent from my iPhoneOn 11. 4. 2023, at 11:38, Manisha ***@***.***> wrote:﻿
I had a spot reserved for 20th April and I don't see it now on RePark. Do I need to book again?

**Comment by manisha-sharma-swi** [comment]
still not there

**Comment by fedorjaro** [comment]
In that case, pls can you reserve it again? Thanks!Sent from my iPhoneOn 11. 4. 2023, at 16:52, Manisha ***@***.***> wrote:﻿
still not there
