### ISSUE TITLE
Can't settle the payments nor share the spot

### ISSUE THREAD

**Issue by jiri-silhan** [fedorjaro/repark-issues#69]
Hi,
I'm getting 403 as a POST response when I try to settle the payment:
![image](https://user-images.githubusercontent.com/16819999/231370275-63dc937c-fd9d-4a6f-a643-91b7e42cf6c3.png)

The same happens when I try to share my spot on a day when someone is waiting for it:
![image](https://user-images.githubusercontent.com/16819999/231370653-51e343e7-7656-4675-8b24-621967bd8aaa.png)

(I've tried logging out and back in but still the same result)

Thanks

**Comment by fedorjaro** [comment]
Should be fixed now. Pls check again.

**Comment by jiri-silhan** [comment]
Thanks for the quick fix. I'm able to settle a payment now, but there is a new problem on that page:
![image](https://user-images.githubusercontent.com/16819999/231680755-389d4dbd-ae64-46c1-897b-9c09212190e6.png)

**Comment by fedorjaro** [comment]
this should be fixed in version 1.8
