### ISSUE TITLE
Wrong total amount when several reservations are paid

### ISSUE THREAD

**Issue by vicocz** [fedorjaro/repark-issues#70]
If I have to pay several reservation to single slot, total amount is wrongly calculated (probably string concatenation instead of sum):
![image](https://user-images.githubusercontent.com/11756608/237016855-cc9b6ad0-ca8e-4a62-b8b0-1bf9f2b0f8c3.png)

QR code says the amount: 151515 as well.

**Comment by fedorjaro** [comment]
Thanks for reporting, should be fixed with v1.10.2.
